blog/urls.py
from django.urls import path,include
from .views import ArticleList,CategoryList,AuthorList
from .views import show_article_detail,show_contact_page,show_base_page
from . import views

#api
from rest_framework import routers
router = routers.DefaultRouter()
router.register(r'articles', views.ArticleViewSet)

from .views import test_ajax

app_name="blog"
urlpatterns = [
    path('', ArticleList.as_view(), name="home"),
    path('contact', show_contact_page , name="contact"),
    path('base', show_base_page , name="base"),
    path('page/<int:page>', ArticleList.as_view(), name="home"),
    path('searched_item/', views.search , name="search_view"),
    path('article/<slug:slug>', show_article_detail , name="detail"),
    path('category/<slug:slug>', CategoryList.as_view(), name="category"),
    path('category/<slug:slug>/page/<int:page>', CategoryList.as_view(), name="category"),
    path('author/<slug:username>', AuthorList.as_view(), name="author"),
    path('author/<slug:username>/page/<int:page>', AuthorList.as_view(), name="author"),

    path('test_ajax', test_ajax, name="test_ajax"),
    #api
    path('', include(router.urls)),
]

crawler/urls.py
from django.urls import path
from .views import test

app_name="crawler"
urlpatterns=[
    path('test', test, name='test'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

# from rest_framework import routers
# router = routers.DefaultRouter()

handler404 = 'blog.views.custom_page_not_found_view'


urlpatterns = [
	path('admin/', admin.site.urls),
	path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
    path('poll/', include('poll.urls')),
    path('crawler/', include('crawler.urls')),
    path('', include('presentation_app.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crawler/models.py
from datetime import timezone
from django.db import models

class CrawledArticle(models.Model):
    title = models.CharField(max_length=50, null=True, blank=True, verbose_name="عنوان")
    text = models.TextField(null=True, blank=True, verbose_name="متن")
    link = models.URLField(null=True, blank=True)
    source = models.CharField(null=True, blank=True, max_length=30, verbose_name="منبع")
    created = models.DateTimeField(auto_now_add=True, editable=False, null=True, blank=True)


    def __str__(self):
        return str(self.title)

    
    class Meta:
        verbose_name = "مقاله اینترنتی"
        verbose_name_plural = "مقاله های اینترنتی"

crawler/views.py
# django
from django.shortcuts import render
from .models import CrawledArticle


def test(request):
    articles = CrawledArticle.objects.all().order_by('-created')
    return render(request, "crawler/list.html", {"articles":articles})

templates/crawler/list.html
{% extends '../blog/base.html' %}
{% load static %}
{% block content %}
        <!-- Start Blog Area -->
        <div class="blog-area pt-100 pb-100">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-12">
                        <div class="row">
                            {% for article in articles %}
                                <div class="col-lg-12 col-md-12 blog-more-item">
                                    <div class="single-blog-card">
                                        <div class="blog-image">
                                            <!-- <a href="#"><img src="#" alt="image" width="850" height="650"></a> -->
<!--             
                                            <div class="date">
                                                <span>تاریخ انتشار</span>
                                                <h3>24</h3>
                                                <span>دی</span>
                                            </div> -->
                                        </div>
                                        <div class="blog-content">
                                            <li>توسط: <a href={{article.link}}><span>اسم نویسنده</span></a></li>
                                            <h3>
                                                <a href="#">{{article.title}}</a>
                                            </h3>
                                            <p> {{article.text|safe|truncatewords:20}} </p>
                                            <a href="#" class="blog-btn">مشاهده بیشتر</a>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>


                        <div class="load-more-btn text-start">
                            <a href="#" id="loadmore" class="default-btn">مشاهده بیشتر</a>
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-12">
                        <aside class="widget-area">
                            <div class="widget widget_search">
                                <form class="search-form" method="post" action="{% url 'blog:search_view' %}">
                                    {% csrf_token %}
                                    <input type="search" name="input_search" class="search-field" placeholder="جستجو...">
                                    <button type="submit"><i class="ri-search-line">بجو</i></button>
                                </form>
                            </div>

                            <div class="widget widget_services">
                                <h3 class="widget-title">همه خدمات</h3>

                                <ul class="services-list">
                                    <li>
                                        <a href="blog.html">تعمیر سیستم <i class="ri-arrow-left-s-line"></i></a>
                                    </li>
                                    <li>
                                        <a href="blog.html">نصب سیستم <i class="ri-arrow-left-s-line"></i></a>
                                    </li>
                                    <li>
                                        <a href="blog.html">ارائه خدمات <i class="ri-arrow-left-s-line"></i></a>
                                    </li>
                                    <li>
                                        <a href="blog.html">آزمایش کیفیت <i class="ri-arrow-left-s-line"></i></a>
                                    </li>
                                    <li>
                                        <a href="blog.html">سیستم اسپلیت بدون داکت <i class="ri-arrow-left-s-line"></i></a>
                                    </li>
                                    <li>
                                        <a href="blog.html">تعمیر و نگهداری <i class="ri-arrow-left-s-line"></i></a>
                                    </li>
                                    <li>
                                        <a href="blog.html">سرویس گرمایش <i class="ri-arrow-left-s-line"></i></a>
                                    </li>
                                </ul>
                            </div>

                            <div class="widget widget_kadi_posts_thumb">
                                <h3 class="widget-title">پست های اخیر</h3>
                                {% for article in last_three_articles %}
                                <h4 class="post-title">
                                    <a href="{% url 'blog:detail' article.slug %}">{{ article.description | truncatewords:20 | safe }}</a>
                                </h4>
                                {% endfor %}
                            </div>

                            <div class="widget widget_tag_cloud">
                                <h3 class="widget-title">برچسب ها</h3>
    
                                <div class="tagcloud">
                                    {% for cat in cats %}
                                        <a href="{% url 'blog:category' cat.slug %}">{{cat}}</a>
                                    {% endfor %}
                                </div>
                            </div>

                            <div class="widget widget_contact">
                                <h3>تماس بگیرید</h3>
                                <h4>مشاوره رایگان دریافت کنید</h4>
                                <div class="icon">
                                    <i class="flaticon-headphones"></i>
                                </div>
                                <a href="tel:15143125678">+1 (514) 312-5678</a>
                            </div>
                        </aside>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Blog Area -->
{% endblock %}