blog/urls.py
from django.urls import path,include
from .views import ArticleList,CategoryList,AuthorList
from .views import show_article_detail,show_contact_page,show_base_page
from . import views

#api
from rest_framework import routers
router = routers.DefaultRouter()
router.register(r'articles', views.ArticleViewSet)

from .views import test_ajax

app_name="blog"
urlpatterns = [
    path('', ArticleList.as_view(), name="home"),
    path('contact', show_contact_page , name="contact"),
    path('base', show_base_page , name="base"),
    path('page/<int:page>', ArticleList.as_view(), name="home"),
    path('searched_item/', views.search , name="search_view"),
    path('article/<slug:slug>', show_article_detail , name="detail"),
    path('category/<slug:slug>', CategoryList.as_view(), name="category"),
    path('category/<slug:slug>/page/<int:page>', CategoryList.as_view(), name="category"),
    path('author/<slug:username>', AuthorList.as_view(), name="author"),
    path('author/<slug:username>/page/<int:page>', AuthorList.as_view(), name="author"),

    path('test_ajax', test_ajax, name="test_ajax"),
    #api
    path('', include(router.urls)),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

# from rest_framework import routers
# router = routers.DefaultRouter()

handler404 = 'blog.views.custom_page_not_found_view'


urlpatterns = [
	path('admin/', admin.site.urls),
	path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
    path('poll/', include('poll.urls')),
    path('crawler/', include('crawler.urls')),
    path('', include('presentation_app.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

presentation_app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name="presentation_blog"
urlpatterns=[
    path('', views.show_main_page, name='main_page'),
    path('services', views.show_services, name='services'),
    path('detail-services', views.show_services_detail, name='service-detail'),
    path('shop', views.show_shop, name='shop'),
    path('detail-shop', views.show_shop_detail, name='shop-detail'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/presentation_blog/services.html
{% extends 'blog/base.html' %}
{% load static %}
{% block header_name %}
محصولات
{% endblock %}
{% block after_home %}
محصولات
{% endblock %}
{% block content %}

        <!-- Start Services Area -->
        <div class="services-area bg-transparent pt-100 pb-100">
            <div class="container">
                <div class="section-title-wrap">
                    <div class="row align-items-center">
                        <div class="col-lg-7">
                            <span>خدمات ما</span>
                            <h2>تمام خدماتی که ما به مشتریان کادی ارائه می دهیم</h2>
                        </div>

                        <div class="col-lg-5">
                            <p>لورم ایپسوم به سادگی ساختار چاپ و متن را در بر می گیرد. لورم ایپسوم به مدت 40 سال استاندارد صنعت بوده است.لورم ایپسوم به سادگی ساختار چاپ و متن را در بر می گیرد.</p>
                        </div>
                    </div>
                </div>

                <div class="row justify-content-center">
                    <div class="col-lg-4 col-md-6 services-more-item">
                        <div class="single-services-card">
                            <a href="{% url 'presentation_blog:service-detail' %}"><img src="{% static 'temp/images/services/services-1.jpg' %}" alt="image"></a>
                            <div class="services-content">
                                <h3>
                                    <a href="services-details.html">نصب سیستم تهویه هوا</a>
                                </h3>
                                <a href="services-details.html" class="add-icon"><i class="ri-add-line"></i></a>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-6 services-more-item">
                        <div class="single-services-card">
                            <a href="{% url 'presentation_blog:service-detail' %}"><img src="{% static 'temp/images/services/services-2.jpg' %}" alt="image"></a>
                            <div class="services-content">
                                <h3>
                                    <a href="{% url 'presentation_blog:service-detail' %}">نگهداری دستگاه تهویه</a>
                                </h3>
                                <a href="{% url 'presentation_blog:service-detail' %}" class="add-icon"><i class="ri-add-line"></i></a>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-6 services-more-item">
                        <div class="single-services-card">
                            <a href="{% url 'presentation_blog:service-detail' %}"><img src="{% static 'temp/images/services/services-3.jpg' %}" alt="image"></a>
                            <div class="services-content">
                                <h3>
                                    <a href="{% url 'presentation_blog:service-detail' %}">نصب دستگاه تهویه</a>
                                </h3>
                                <a href="{% url 'presentation_blog:service-detail' %}" class="add-icon"><i class="ri-add-line"></i></a>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-6 services-more-item">
                        <div class="single-services-card">
                            <a href="{% url 'presentation_blog:service-detail' %}"><img src="{% static 'temp/images/services/services-4.jpg' %}" alt="image"></a>
                            <div class="services-content">
                                <h3>
                                    <a href="{% url 'presentation_blog:service-detail' %}">سیستم های تهویه</a>
                                </h3>
                                <a href="{% url 'presentation_blog:service-detail' %}" class="add-icon"><i class="ri-add-line"></i></a>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-6 services-more-item">
                        <div class="single-services-card">
                            <a href="{% url 'presentation_blog:service-detail' %}"><img src="{% static 'temp/images/services/services-5.jpg' %}" alt="image"></a>
                            <div class="services-content">
                                <h3>
                                    <a href="{% url 'presentation_blog:service-detail' %}">نصب سیستم تهویه</a>
                                </h3>
                                <a href="{% url 'presentation_blog:service-detail' %}" class="add-icon"><i class="ri-add-line"></i></a>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-6 services-more-item">
                        <div class="single-services-card">
                            <a href="{% url 'presentation_blog:service-detail' %}"><img src="{% static 'temp/images/services/services-6.jpg' %}" alt="image"></a>
                            <div class="services-content">
                                <h3>
                                    <a href="#">تعمیر و نگهداری</a>
                                </h3>
                                <a href="{% url 'presentation_blog:service-detail' %}" class="add-icon"><i class="ri-add-line"></i></a>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-6 services-more-item">
                        <div class="single-services-card">
                            <a href="{% url 'presentation_blog:service-detail' %}"><img src="{% static 'temp/images/services/services-1.jpg' %}" alt="image"></a>
                            <div class="services-content">
                                <h3>
                                    <a href="{% url 'presentation_blog:service-detail' %}">تعمیر دستگاه</a>
                                </h3>
                                <a href="{% url 'presentation_blog:service-detail' %}" class="add-icon"><i class="ri-add-line"></i></a>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-6 services-more-item">
                        <div class="single-services-card">
                            <a href="{% url 'presentation_blog:service-detail' %}"><img src="{% static 'temp/images/services/services-2.jpg' %}" alt="image"></a>
                            <div class="services-content">
                                <h3>
                                    <a href="{% url 'presentation_blog:service-detail' %}">سیستم تهویه مطبوع</a>
                                </h3>
                                <a href="{% url 'presentation_blog:service-detail' %}" class="add-icon"><i class="ri-add-line"></i></a>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-6 services-more-item">
                        <div class="single-services-card">
                            <a href="{% url 'presentation_blog:service-detail' %}"><img src="{% static 'temp/images/services/services-3.jpg' %}" alt="image"></a>
                            <div class="services-content">
                                <h3>
                                    <a href="{% url 'presentation_blog:service-detail' %}">نصب سیستم تهویه</a>
                                </h3>
                                <a href="{% url 'presentation_blog:service-detail' %}" class="add-icon"><i class="ri-add-line"></i></a>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-6 services-more-item">
                        <div class="single-services-card">
                            <a href="{% url 'presentation_blog:service-detail' %}"><img src="{% static 'temp/images/services/services-4.jpg' %}" alt="image"></a>
                            <div class="services-content">
                                <h3>
                                    <a href="{% url 'presentation_blog:service-detail' %}">نصب دستگاه تهویه</a>
                                </h3>
                                <a href="{% url 'presentation_blog:service-detail' %}" class="add-icon"><i class="ri-add-line"></i></a>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-6 services-more-item">
                        <div class="single-services-card">
                            <a href="{% url 'presentation_blog:service-detail' %}"><img src="{% static 'temp/images/services/services-5.jpg' %}" alt="image"></a>
                            <div class="services-content">
                                <h3>
                                    <a href="{% url 'presentation_blog:service-detail' %}">نصب فوری قطعات</a>
                                </h3>
                                <a href="{% url 'presentation_blog:service-detail' %}" class="add-icon"><i class="ri-add-line"></i></a>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-6 services-more-item">
                        <div class="single-services-card">
                            <a href="{% url 'presentation_blog:service-detail' %}"><img src="{% static 'temp/images/services/services-6.jpg' %}" alt="image"></a>
                            <div class="services-content">
                                <h3>
                                    <a href="{% url 'presentation_blog:service-detail' %}">نگهداری دستگاه تهویه</a>
                                </h3>
                                <a href="{% url 'presentation_blog:service-detail' %}" class="add-icon"><i class="ri-add-line"></i></a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="load-more-btn">
                    <a href="#" id="loadmore" class="default-btn">مشاهده بیشتر</a>
                </div>
            </div>
        </div>
        <!-- End Services Area -->


{% endblock %}

templates/presentation_blog/shop.html
{% extends 'blog/base.html' %}
{% load static %}
{% block header_name %}
فروشگاه
{% endblock %}
{% block after_home %}
فروشگاه
{% endblock %}
{% block content %}

        <!-- Start Shop Area -->
        <div class="shop-area ptb-100">
            <div class="container">
                <div class="kadi-grid-sorting row align-items-center">
                    <div class="col-lg-8 col-md-6 result-count">
                        <p>ما <span class="count">6</span> محصول را در دسترس قرار دادیم</p>
                    </div>

                    <div class="col-lg-4 col-md-6 ordering">
                        <select class="selectize-filter">
                            <option value="">مرتب سازی بر اساس</option>
                            <option value="2">محصولات محبوب</option>
                            <option value="3">محصولات پرطرفدار</option>
                            <option value="5">محصولات پرفروش</option>
                            <option value="6">پیش فرض</option>
                            <option value="7">جدیدترین</option>
                            <option value="8">محصولات پیشنهادی</option>
                            <option value="9">قیمت: کمترین</option>
                            <option value="10">قیمت: بیشترین</option>
                        </select>
                    </div>
                </div>

                <div class="row justify-content-center">
                    <div class="col-lg-4 col-md-6">
                        <div class="single-shop-card">
                            <div class="shop-image">
                                <a href="{% url 'presentation_blog:shop-detail' %}"><img src="{% static 'temp/images/shop/shop-1.png' %}" alt="image"></a>
                            </div>
                            <div class="shop-content">
                                <h3>
                                    <a href="{% url 'presentation_blog:shop-detail' %}">دستگاه تصفیه هوا</a>
                                </h3>
                                <span>1900 تومان</span>
    
                                <div class="cart-icon">
                                    <a href="cart.html"><i class="ri-shopping-cart-line"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-6">
                        <div class="single-shop-card">
                            <div class="shop-image">
                                <a href="{% url 'presentation_blog:shop-detail' %}"><img src="{% static 'temp/images/shop/shop-2.png' %}" alt="image"></a>
                            </div>
                            <div class="shop-content">
                                <h3>
                                    <a href="{% url 'presentation_blog:shop-detail' %}">سیستم تهویه هوا</a>
                                </h3>
                                <span>1300 تومان</span>
    
                                <div class="cart-icon">
                                    <a href="cart.html"><i class="ri-shopping-cart-line"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-6">
                        <div class="single-shop-card">
                            <div class="shop-image">
                                <a href="{% url 'presentation_blog:shop-detail' %}"><img src="{% static 'temp/images/shop/shop-3.png' %}" alt="image"></a>
                            </div>
                            <div class="shop-content">
                                <h3>
                                    <a href="{% url 'presentation_blog:shop-detail' %}">فن تهویه فضای باز</a>
                                </h3>
                                <span>2200 تومان</span>
    
                                <div class="cart-icon">
                                    <a href="cart.html"><i class="ri-shopping-cart-line"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-6">
                        <div class="single-shop-card">
                            <div class="shop-image">
                                <a href="{% url 'presentation_blog:shop-detail' %}"><img src="{% static 'temp/images/shop/shop-4.png' %}" alt="image"></a>
                            </div>
                            <div class="shop-content">
                                <h3>
                                    <a href="{% url 'presentation_blog:shop-detail' %}">فیلتر گرد و غبار</a>
                                </h3>
                                <span>2600 تومان</span>
    
                                <div class="cart-icon">
                                    <a href="cart.html"><i class="ri-shopping-cart-line"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-6">
                        <div class="single-shop-card">
                            <div class="shop-image">
                                <a href="{% url 'presentation_blog:shop-detail' %}"><img src="{% static 'temp/images/shop/shop-5.png' %}" alt="image"></a>
                            </div>
                            <div class="shop-content">
                                <h3>
                                    <a href="#">کنترل از راه دور</a>
                                </h3>
                                <span>3900 تومان</span>
    
                                <div class="cart-icon">
                                    <a href="cart.html"><i class="ri-shopping-cart-line"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-6">
                        <div class="single-shop-card">
                            <div class="shop-image">
                                <a href="{% url 'presentation_blog:shop-detail' %}"><img src="{% static 'temp/images/shop/shop-6.png' %}" alt="image"></a>
                            </div>
                            <div class="shop-content">
                                <h3>
                                    <a href="{% url 'presentation_blog:shop-detail' %}">ترموستات دیجیتال</a>
                                </h3>
                                <span>6900 تومان</span>
    
                                <div class="cart-icon">
                                    <a href="cart.html"><i class="ri-shopping-cart-line"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-6">
                        <div class="single-shop-card">
                            <div class="shop-image">
                                <a href="{% url 'presentation_blog:shop-detail' %}"><img src="{% static 'temp/images/shop/shop-7.png' %}" alt="image"></a>
                            </div>
                            <div class="shop-content">
                                <h3>
                                    <a href="{% url 'presentation_blog:shop-detail' %}">فیلتر جاروبرقی</a>
                                </h3>
                                <span>3300 تومان</span>
    
                                <div class="cart-icon">
                                    <a href="cart.html"><i class="ri-shopping-cart-line"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-6">
                        <div class="single-shop-card">
                            <div class="shop-image">
                                <a href="{% url 'presentation_blog:shop-detail' %}"><img src="{% static 'temp/images/shop/shop-8.png' %}" alt="image"></a>
                            </div>
                            <div class="shop-content">
                                <h3>
                                    <a href="{% url 'presentation_blog:shop-detail' %}">منبع تغذیه</a>
                                </h3>
                                <span>9900 تومان</span>
    
                                <div class="cart-icon">
                                    <a href="cart.html"><i class="ri-shopping-cart-line"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-6">
                        <div class="single-shop-card">
                            <div class="shop-image">
                                <a href="{% url 'presentation_blog:shop-detail' %}"><img src="{% static 'temp/images/shop/shop-1.png' %}" alt="image"></a>
                            </div>
                            <div class="shop-content">
                                <h3>
                                    <a href="{% url 'presentation_blog:shop-detail' %}">دستگاه تصفیه هوا</a>
                                </h3>
                                <span>1900 تومان</span>
    
                                <div class="cart-icon">
                                    <a href="cart.html"><i class="ri-shopping-cart-line"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <div class="pagination-area">
                            <a href="shop.html" class="prev page-numbers"><i class="ri-arrow-right-s-line"></i></a>
                            <span class="page-numbers current" aria-current="page">1</span>
                            <a href="shop.html" class="page-numbers">2</a>
                            <a href="shop.html" class="page-numbers">3</a>
                            <a href="shop.html" class="next page-numbers"><i class="ri-arrow-left-s-line"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Shop Area -->


{% endblock %}