blog/urls.py
from django.urls import path,include
from .views import ArticleList,CategoryList,AuthorList
from .views import show_article_detail,show_contact_page,show_base_page
from . import views

#api
from rest_framework import routers
router = routers.DefaultRouter()
router.register(r'articles', views.ArticleViewSet)

from .views import test_ajax

app_name="blog"
urlpatterns = [
    path('', ArticleList.as_view(), name="home"),
    path('contact', show_contact_page , name="contact"),
    path('base', show_base_page , name="base"),
    path('page/<int:page>', ArticleList.as_view(), name="home"),
    path('searched_item/', views.search , name="search_view"),
    path('article/<slug:slug>', show_article_detail , name="detail"),
    path('category/<slug:slug>', CategoryList.as_view(), name="category"),
    path('category/<slug:slug>/page/<int:page>', CategoryList.as_view(), name="category"),
    path('author/<slug:username>', AuthorList.as_view(), name="author"),
    path('author/<slug:username>/page/<int:page>', AuthorList.as_view(), name="author"),

    path('test_ajax', test_ajax, name="test_ajax"),
    #api
    path('', include(router.urls)),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

# from rest_framework import routers
# router = routers.DefaultRouter()

handler404 = 'blog.views.custom_page_not_found_view'


urlpatterns = [
	path('admin/', admin.site.urls),
	path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
    path('poll/', include('poll.urls')),
    path('crawler/', include('crawler.urls')),
    path('', include('presentation_app.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from datetime import date
from django.db import models
from django.urls import reverse
from django.utils.html import format_html
from django.utils import timezone
from account.models import User
from extensions.utils import jalali_converter


# my managers subclass
class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='p')


class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status=True)



class Article(models.Model):
    STATUS_CHOICES={
        ('d','پیش نویس'),
        ('p','منتشر شده'),
    }
    author     =models.ForeignKey(User,null=True,on_delete=models.SET_NULL,related_name='articles',verbose_name='نویسنده')
    title      =models.CharField(max_length=200, verbose_name="عنوان")
    slug       =models.SlugField(max_length=100,unique=True, verbose_name="آدرس")
    category   =models.ManyToManyField('Category',verbose_name="دسته بندی", related_name="articles")
    description=models.TextField(verbose_name="محتوا")
    thumbnail  =models.ImageField(upload_to="images",verbose_name="تصویر")
    publish    =models.DateTimeField(default=timezone.now, verbose_name="زمان انتشار")
    created    =models.DateTimeField(auto_now_add=True)
    updated    =models.DateTimeField(auto_now=True)
    status     =models.CharField(max_length=1 ,choices=STATUS_CHOICES, verbose_name="وضعیت")


    class Meta:
        verbose_name       ="مقاله"
        verbose_name_plural="مقالات"
        ordering           =['-publish']


    def jpublish(self):
        return jalali_converter(self.publish)
    jpublish.short_description="زمان انتشار"


#    def category_published(self):
#        return self.category.filter(status=True)

    def thumbnail_tag(self):
        return format_html("<img width=100 height=75 style='border-radius: 5px;' src='{}'>".format(self.thumbnail.url))
    thumbnail_tag.short_description="عکس"

    def category_to_str(self):
        return ",".join([category.title for category in self.category.active()])
    category_to_str.short_description="دسته بندی"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("account:home")


    objects=ArticleManager()


class Comment(models.Model):
    user=models.ForeignKey(User , blank=True , null=True,on_delete=models.SET_NULL,verbose_name='یوزر')
    article=models.ForeignKey(Article , on_delete=models.CASCADE , related_name="comments" , verbose_name="مقاله" , null=True , blank=True)
    name=models.CharField(max_length=255, verbose_name="نام" , blank=False , null=False)
    body=models.TextField(verbose_name="متن" , blank=False , null=False)
    date_added=models.DateTimeField(auto_now_add=True , verbose_name="زمان نوشتن" , null=True , blank=True)

    class Meta:
        verbose_name="کامنت"
        verbose_name_plural="کامنت ها"
        ordering=['date_added']

    def __str__(self) -> str:
        return f"{self.body} | {self.name}"



class Category(models.Model):
    parent     =models.ForeignKey('self' , default=None , null=True , blank=True, on_delete=models.SET_NULL ,related_name='children', verbose_name='زیردست')
    title      =models.CharField(max_length=200, verbose_name="عنوان")
    slug       =models.SlugField(max_length=100,unique=True, verbose_name="آدرس")
    status     =models.BooleanField(default=True, verbose_name="آیا نمایش داده شود؟")
    position   =models.IntegerField(verbose_name="پوزیشن")

    class Meta:
        verbose_name       ="دسته بندی"
        verbose_name_plural="دسته بندی ها"
        ordering           =['parent__id','position']

    def __str__(self):
        return self.title

    objects=CategoryManager()

blog/forms.py
from django import forms
from .models import Comment
 
class CommentForm(forms.ModelForm):
    # content = forms.CharField(label ="", widget = forms.Textarea(
    # attrs ={
    #     'class':'form-control',
    #     'rows':4,
    #     'cols':50
    # }))
    class Meta:
        model = Comment
        exclude =("user",)

blog/views.py
from django.shortcuts import render, get_object_or_404 , get_list_or_404
from .models import Article,Category
from account.models import User
from django.views.generic import ListView
from .forms import CommentForm


#api
from rest_framework import viewsets
from rest_framework import permissions
from .serializers import ArticleSerializer


#404 view
def custom_page_not_found_view(request, exception):
    return render(request, "blog/404.html",{})


class ArticleList(ListView):
	template_name="blog/blog.html"
	queryset     	   =Article.objects.published()
	paginate_by  	   =3

	def get_context_data(self,**kwargs):
		context = super(ArticleList,self).get_context_data(**kwargs)
		context['last_three_articles'] = Article.objects.published().order_by('-publish')[0:3]
		context['cats'] = Category.objects.all()
		return context


def show_article_detail(request , slug):
	if request.method == 'POST':
		MyCommentForm=CommentForm(request.POST or None)
		if MyCommentForm.is_valid():
			mc=MyCommentForm.save(commit=False)	
			mc.article=get_object_or_404(Article.objects.all() , slug=slug)
			mc.save()
		else:
			MyCommentForm=CommentForm(request.POST or None)

	context={
		"article":get_object_or_404(Article.objects.published() , slug=slug),
		"cats":Category.objects.all(),
	}
	return render(request , "blog/blog-details.html" , context)


'''
def category(request, slug ,page=1):
	category     =get_object_or_404(Category, slug=slug ,status=True)
	articles_list=category.articles.published()
	paginator    = Paginator(articles_list, 3) # Show 3 contacts per
	articles     = paginator.get_page(page)
	context={
		"category":category,
		"articles":articles,
	}
	return render(request,"blog/category.html",context)'''


class CategoryList(ListView):
	paginate_by = 3
	template_name='blog/category-list.html'

	def get_queryset(self):
		global category
		slug=self.kwargs.get('slug')
		category=get_object_or_404(Category.objects.active() , slug=slug)
		return category.articles.published()

	def get_context_data(self, **kwargs):
		context=super().get_context_data(**kwargs)
		context['category']=category
		return context


class AuthorList(ListView):
	paginate_by = 3
	template_name = 'blog/author_list.html'

	def get_queryset(self):
		global author
		username = self.kwargs.get('username')
		author = get_object_or_404(User, username=username)
		return author.articles.published()

	def get_context_data(self, **kwargs):
		context=super().get_context_data(**kwargs)
		context['author']=author
		return context


def show_contact_page(request):
	return render(request, "blog/contact.html" )


def show_base_page(request):
	return render(request, "blog/base.html" )


def search(request):
	found_articles = Article.objects.none()
	if request.method == "POST":
		input_word = request.POST.get("input_search")
		found_articles = Article.objects.filter(title__contains = input_word)

	if found_articles:
		return render(request , "blog/search_articles.html" , {'object_list':found_articles})
	return render(request , "blog/search_not_found.html")


#api_views
class ArticleViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Article.objects.all().order_by('-created')
    serializer_class = ArticleSerializer
    # permission_classes = [permissions.IsAuthenticated]


def test_ajax(request):
	return render(request, "blog/article_list_axios.html")

templates/blog/article_list.html
{% extends 'blog/list.html' %}

{% block header %}{% endblock %}



{% block previous_page_url %}
{% url 'blog:home'   page_obj.previous_page_number %}
{% endblock %}


{% block next_page_url %}
{% url 'blog:home'   page_obj.next_page_number %}
{% endblock %}

templates/blog/article_list_axios.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>This is a test</h2>
    <button onclick="getArticles()">Show Something</button>
</body>

<!-- import axios cdn -->
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script>
    const getArticles = () => {
        axios.get('/blog/articles')
        // axios.get('http://127.0.0.1:8000/blog/articles')
            .then(Response =>{
                const articles = Response.data.results;
                for (article of articles){
                    console.log(article)
                }
            })
            .catch(error => console.error(error));
        }
</script>
</html>

templates/blog/author_list.html
{% extends 'blog/list.html' %}



{% block header %}
<h3 style="font-family: 'Sahel';" class="alert alert-primary text-center">نویسنده:{{author.get_full_name}}</h3>
{% endblock %}

{% block name %}
{{article.author}}
{% endblock %}

{% block previous_page_url %}
{% url 'blog:author' author.username  page_obj.previous_page_number %}
{% endblock %}

{% block next_page_url %}
{% url 'blog:author' author.username  page_obj.next_page_number %}
{% endblock %}

templates/blog/blog-details.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}

        <!-- Start Blog Details Area -->
        <div class="blog-details-area pt-100 pb-100">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-12">
                        <div class="blog-details-desc">
                            <div class="article-content">
                                <div class="article-image">
                                    <img src="{{article.thumbnail.url}}" width="856" height="" alt="image">
                                </div>
                                <ul class="entry-meta">
                                    <li>توسط: <a href="author.html">{{ article.author.get_full_name }}</a></li>
                                    <li>(02) نظر</li>
                                </ul>
                                <h3>{{article.title}}</h3>
                                <p>
                                    {{article.description | safe}}
                                </p>
                                </div>
                            <div class="row align-items-center">
                                <div class="col-lg-6 col-md-6">
                                    <div class="article-tags">
                                        <ul>
                                            <li><span>برچسب ها:</span></li>
                                            {% for cat in article.category.all %}
                                                <li><a href="{% url 'blog:category' cat.slug %}">{{cat.title}}</a></li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>

                                <div class="col-lg-6 col-md-6">
                                    <div class="article-share">
                                        <ul>
                                            <li><span>اشترک گذاری:</span></li>
                                            <li>
                                                <a href="https://www.facebook.com/" target="_blank">
                                                    <i class="ri-facebook-fill"></i>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="https://twitter.com/?lang=en" target="_blank">
                                                    <i class="ri-twitter-fill"></i>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="https://www.instagram.com/" target="_blank">
                                                    <i class="ri-instagram-line"></i>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="https://www.linkedin.com/signup" target="_blank">
                                                    <i class="ri-linkedin-line"></i>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>

                            <div class="article-comments">
                                <h3>نظرات کاربران</h3>
                                {% for comment in article.comments.all %}
                                    <div class="comments-list">
                                        <img src="{% static 'temp/images/testimonial/image-1.jpg' %}" alt="image">
                                        <h5>{{comment.name}}</h5>
                                        <span>{{comment.date_added}}</span>
                                        <p>{{comment.body}}</p>
                                        <a href="#" class="reply-btn"><i class="ri-reply-line"></i> پاسخ</a>
                                    </div>
                                {% endfor %}
                            </div>

                            <div class="article-leave-comment">
                                <h3>نظر بدهید</h3>
                                <p>آدرس ایمیل شما منتشر نخواهد شد.موارد الزامی  مشخص شده اند *</p>
                                
                                <form action="{% url 'blog:detail' article.slug %}" method="post">
                                    {% csrf_token %}
                                    <div class="row justify-content-center">
                                        <div class="col-lg-6 col-md-12">
                                            <div class="form-group">
                                                <label>نام</label>
                                                <input type="text" class="form-control" name="name">
                                            </div>
                                        </div>

                                        <div class="col-lg-6 col-md-12">
                                            <div class="form-group">
                                                <label>ایمیل</label>
                                                <input type="text" class="form-control">
                                            </div>
                                        </div>

                                        <div class="col-lg-12 col-md-12">
                                            <div class="form-group">
                                                <label>وبسایت</label>
                                                <input type="text" class="form-control">
                                            </div>
                                        </div>

                                        <div class="col-lg-12 col-md-12">
                                            <div class="form-group">
                                                <label>نظر شما</label>
                                                <textarea name="body" class="form-control">
                                                </textarea>
                                            </div>
                                        </div>
    
                                        <div class="col-lg-12 col-md-12">
                                            <button type="submit" class="default-btn">ارسال</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-12">
                        <aside class="widget-area">
                            <div class="widget widget_search">
                                <form class="search-form">
                                    <input type="search" class="search-field" placeholder="جستجو...">
                                    <button type="submit"><i class="ri-search-line"></i></button>
                                </form>
                            </div>

                            <div class="widget widget_services">
                                <h3 class="widget-title">همه خدمات</h3>

                                <ul class="services-list">
                                    <li>
                                        <a href="blog.html">تعمیر سیستم <i class="ri-arrow-left-s-line"></i></a>
                                    </li>
                                    <li>
                                        <a href="blog.html">نصب سیستم <i class="ri-arrow-left-s-line"></i></a>
                                    </li>
                                    <li>
                                        <a href="blog.html">ارائه خدمات <i class="ri-arrow-left-s-line"></i></a>
                                    </li>
                                    <li>
                                        <a href="blog.html">آزمایش کیفیت <i class="ri-arrow-left-s-line"></i></a>
                                    </li>
                                    <li>
                                        <a href="blog.html">سیستم اسپلیت بدون داکت <i class="ri-arrow-left-s-line"></i></a>
                                    </li>
                                    <li>
                                        <a href="blog.html">تعمیر و نگهداری <i class="ri-arrow-left-s-line"></i></a>
                                    </li>
                                    <li>
                                        <a href="blog.html">سرویس گرمایش <i class="ri-arrow-left-s-line"></i></a>
                                    </li>
                                </ul>
                            </div>

                            <div class="widget widget_kadi_posts_thumb">
                                <h3 class="widget-title">پست های اخیر</h3>
    
                                <h4 class="post-title">
                                    <a href="blog-details.html">5 نکته وجود دارد که باید در مورد تهویه هوا و انواع سیستم ها بدانید</a>
                                </h4>
                                <h4 class="post-title">
                                    <a href="blog-details.html">5 نکته وجود دارد که باید در مورد تهویه هوا و انواع سیستم ها بدانید</a>
                                </h4>
                                <h4 class="post-title">
                                    <a href="blog-details.html">5 نکته وجود دارد که باید در مورد تهویه هوا و انواع سیستم ها بدانید</a>
                                </h4>
                            </div>

                            <div class="widget widget_tag_cloud">
                                <h3 class="widget-title">برچسب ها</h3>
    
                                <div class="tagcloud">
                                    {% for cat in cats %}
                                        <a href="{% url 'blog:category' cat.slug %}">{{cat}}</a>
                                    {% endfor %}
                                </div>
                            </div>

                            <div class="widget widget_contact">
                                <h3>تماس بگیرید</h3>
                                <h4>مشاوره رایگان دریافت کنید</h4>
                                <div class="icon">
                                    <i class="flaticon-headphones"></i>
                                </div>
                                <a href="tel:15143125678">+1 (514) 312-5678</a>
                            </div>
                        </aside>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Blog Details Area -->

{% endblock %}

templates/blog/blog.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
        <!-- Start Blog Area -->
        <div class="blog-area pt-100 pb-100">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-12">
                        <div class="row">
                            {% for article in object_list %}
                                <div class="col-lg-12 col-md-12 blog-more-item">
                                    <div class="single-blog-card">
                                        <div class="blog-image">
                                            <a href="{% url 'blog:detail' article.slug %}"><img src="{{ article.thumbnail.url }}" alt="image" width="850" height="650"></a>
            
                                            <div class="date">
                                                {{article.jpublish}}
                                                <h3>24</h3>
                                                <span>دی</span>
                                            </div>
                                        </div>
                                        <div class="blog-content">
                                            <ul class="entry-meta">
                                                <li>توسط: <a href="blog.html">{{ article.author.get_full_name }}</a>  /  ({{article.comments.all.count}}) نظر</li>
                                            </ul>
                                            <h3>
                                                <a href="{% url 'blog:detail' article.slug %}">{{article.title}}</a>
                                            </h3>
                                            <p> {{article.description|safe|truncatewords:40}} </p>
                                            <a href="{% url 'blog:detail' article.slug %}" class="blog-btn">مشاهده بیشتر</a>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>


                        <div class="load-more-btn text-start">
                            <a href="#" id="loadmore" class="default-btn">مشاهده بیشتر</a>
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-12">
                        <aside class="widget-area">
                            <div class="widget widget_search">
                                <form class="search-form">
                                    <input type="search" class="search-field" placeholder="جستجو...">
                                    <button type="submit"><i class="ri-search-line"></i></button>
                                </form>
                            </div>

                            <div class="widget widget_services">
                                <h3 class="widget-title">همه خدمات</h3>

                                <ul class="services-list">
                                    <li>
                                        <a href="blog.html">تعمیر سیستم <i class="ri-arrow-left-s-line"></i></a>
                                    </li>
                                    <li>
                                        <a href="blog.html">نصب سیستم <i class="ri-arrow-left-s-line"></i></a>
                                    </li>
                                    <li>
                                        <a href="blog.html">ارائه خدمات <i class="ri-arrow-left-s-line"></i></a>
                                    </li>
                                    <li>
                                        <a href="blog.html">آزمایش کیفیت <i class="ri-arrow-left-s-line"></i></a>
                                    </li>
                                    <li>
                                        <a href="blog.html">سیستم اسپلیت بدون داکت <i class="ri-arrow-left-s-line"></i></a>
                                    </li>
                                    <li>
                                        <a href="blog.html">تعمیر و نگهداری <i class="ri-arrow-left-s-line"></i></a>
                                    </li>
                                    <li>
                                        <a href="blog.html">سرویس گرمایش <i class="ri-arrow-left-s-line"></i></a>
                                    </li>
                                </ul>
                            </div>

                            <div class="widget widget_kadi_posts_thumb">
                                <h3 class="widget-title">پست های اخیر</h3>
                                {% for article in last_three_articles %}
                                <h4 class="post-title">
                                    <a href="{% url 'blog:detail' article.slug %}">{{ article.description | truncatewords:20 | safe }}</a>
                                </h4>
                                {% endfor %}
                            </div>

                            <div class="widget widget_tag_cloud">
                                <h3 class="widget-title">برچسب ها</h3>
    
                                <div class="tagcloud">
                                    {% for cat in cats %}
                                        <a href="{% url 'blog:category' cat.slug %}">{{cat}}</a>
                                    {% endfor %}
                                </div>
                            </div>

                            <div class="widget widget_contact">
                                <h3>تماس بگیرید</h3>
                                <h4>مشاوره رایگان دریافت کنید</h4>
                                <div class="icon">
                                    <i class="flaticon-headphones"></i>
                                </div>
                                <a href="tel:15143125678">+1 (514) 312-5678</a>
                            </div>
                        </aside>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Blog Area -->
{% endblock %}

templates/blog/category_list.html
{% extends 'blog/list.html' %}



{% block header %}

<h3 style="font-family: Sahel;" class="alert alert-primary text-center">دسته بندی:{{category.title}}</h3>

{% endblock %}


{% block previous_page_url %}
    {% url 'blog:category' category.slug  page_obj.previous_page_number %}
{% endblock %}

{% block next_page_url %}
    {% url 'blog:category' category.slug  page_obj.next_page_number %}
{% endblock %}


templates/blog/list.html
{% extends 'blog/base.html' %}
{% load static %}
{% block main %}
<!-- Page Header -->
<header class="masthead" style="background-image:url('{% static "img/uni2.jpg" %}')">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h1 style=" font-family:'Sahel'">سامانه اساتید</h1>
                    <h6 style=" font-family:'Sahel'">دانشگاه هوایی شهید ستاری</h6>
                </div>
            </div>
        </div>
    </div>
</header>


<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            {% block header %}

            {% endblock %}

            {% for article in object_list %}
            <div class="post-preview">
                <a href="{% url 'blog:detail' article.slug %}">
                    <h2 class="post-title">
                        <p style=" font-family:'Sahel'">{{article.title}}</p>
                    </h2>
                    <h3 style=" font-family:'Sahel'" class="post-subtitle">
                        {{article.description|safe|truncatewords:40}}
                    </h3>
                </a>
                <p class="post-meta">نوشته شده توسط
                    <a href="{% url 'blog:author' article.author %}">{{ article.author.get_full_name }}</a>
                    {{article.jpublish}}</p>
                <div>
                    {% for cat in article.category.active %}
                    <a href="{% url 'blog:category' cat.slug %}">#{{cat.title}}</a>
                    {% endfor %}
                </div>
            </div>

            {% endfor %}
            <!-- Pager -->
            <!-- Pager -->
            {% if is_paginated %}
                <div class="clearfix pager-botton">
                    {% if page_obj.has_previous %}
                    <a class="btn btn-primary float-right ml-3"
                        href="{% block previous_page_url %}{% endblock %}">پست های جدید &rarr;</a>
                    {% endif %}
                    {% if page_obj.has_next %}
                    <a class="btn btn-primary float-right "
                        href="{% block next_page_url %}{% endblock %}">پست های قدیمی &larr;</a>
                    {% endif %}
                </div>
            {% endif %}
        </div>
    </div>
</div>


{% endblock %}