account/urls.py
from django.contrib.auth import views
from django.urls import path, include
from .views import ArticlelList,ArticleCreate,ArticleUpdate,ArticleDelete,Profile

from django.conf.urls.static import static
from django.conf import settings

from .views import UserViewSet, edit_mainpage

# api import
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)


app_name="account"
urlpatterns=[
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('article/create', ArticleCreate.as_view(), name='article-create'),
    path('article/update/<int:pk>', ArticleUpdate.as_view(), name="article-update"),
    path('article/delete/<int:pk>', ArticleDelete.as_view(), name="article-delete"),
    path('profile', Profile.as_view(), name="profile"),
    path('', ArticlelList.as_view(), name="home"),
    path('edit_main-page', edit_mainpage, name="edit_main"),
]


urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


blog/urls.py
from django.urls import path,include
from .views import ArticleList,CategoryList,AuthorList
from .views import show_article_detail,show_contact_page,show_base_page
from . import views

#api
from rest_framework import routers
router = routers.DefaultRouter()
router.register(r'articles', views.ArticleViewSet)

from .views import test_ajax

app_name="blog"
urlpatterns = [
    path('', ArticleList.as_view(), name="home"),
    path('contact', show_contact_page , name="contact"),
    path('base', show_base_page , name="base"),
    path('page/<int:page>', ArticleList.as_view(), name="home"),
    path('searched_item/', views.search , name="search_view"),
    path('article/<slug:slug>', show_article_detail , name="detail"),
    path('category/<slug:slug>', CategoryList.as_view(), name="category"),
    path('category/<slug:slug>/page/<int:page>', CategoryList.as_view(), name="category"),
    path('author/<slug:username>', AuthorList.as_view(), name="author"),
    path('author/<slug:username>/page/<int:page>', AuthorList.as_view(), name="author"),

    path('test_ajax', test_ajax, name="test_ajax"),
    #api
    path('', include(router.urls)),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

# from rest_framework import routers
# router = routers.DefaultRouter()

handler404 = 'blog.views.custom_page_not_found_view'


urlpatterns = [
	path('admin/', admin.site.urls),
	path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
    path('poll/', include('poll.urls')),
    path('crawler/', include('crawler.urls')),
    path('', include('presentation_app.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

poll/urls.py
from django.urls import path,include
from .views import home,create,vote,results


app_name="poll"
urlpatterns = [
path('home', home, name='home'),
path('create/', create, name='create'),
path('vote/<poll_id>/', vote, name='vote'),
path('results/<poll_id>/', results, name='results'),
]

poll/models.py
from django.db import models



class Poll(models.Model):
    question = models.TextField()
    option_one = models.CharField(max_length=30)
    option_two = models.CharField(max_length=30)
    option_three = models.CharField(max_length=30)
    option_one_count = models.IntegerField(default=0)
    option_two_count = models.IntegerField(default=0)
    option_three_count = models.IntegerField(default=0)


    def total(self):
        return self.option_one_count + self.option_two_count + self.option_three_count

    def __str__(self):
        return (self.question)

    class Meta:
        verbose_name="نظرسنجی"
        verbose_name_plural="نظرسنجی ها"
#        unique_together=['name','id']

poll/forms.py
from django.forms import ModelForm
from .models import Poll

class PollForm(ModelForm):
    class Meta:
        model=Poll
        fields=['question','option_one','option_two','option_three']
        
    

poll/views.py
from django.shortcuts import render
from .forms import PollForm
from .models import Poll
from django.shortcuts import redirect
from django.http import HttpResponse
from django.contrib import messages

 
def home(request):
    polls=Poll.objects.all()
    context={
        'polls':polls,
    }
    return render(request,'home.html',context)



def create(request):
    if request.method == 'POST':
        form=PollForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('poll:home')
    else:
        form=PollForm()

    form=PollForm
    context={
        'form':form,   
    }
    return render(request,'create.html',context)


def vote(request, poll_id):
    poll=Poll.objects.get(pk=poll_id)


    if request.method == 'POST':
        selected_option=request.POST['poll']
        if selected_option=='option1':
            poll.option_one_count+=1
            
        elif selected_option=='option2':
            poll.option_two_count+=1
        elif selected_option=='option3':
            poll.option_three_count+=1
        else:
            return HttpResponse(400,'Invalid Form')
        poll.save()
        return redirect('poll:results', poll.id)

    context={
        'poll':poll
    }
    return render(request,'vote.html',context)




def results(request, poll_id):
    poll=Poll.objects.get(pk=poll_id)
    context={
        'poll':poll,
    }
    return render(request,'results.html',context)

poll/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <style>
    @import url('https://cdn.fontcdn.ir/Font/Persian/Sahel/Sahel.css');
    body {
    text-align: right !important;
    direction: rtl !important;
    font-family: Sahel !important;
}

  </style>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block title-meta %}عنوان صفحه{% endblock %}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'registration/adminlte/plugins/fontawesome-free/css/all.min.css'%}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bbootstrap 4 -->
  <link rel="stylesheet" href="{% static 'registration/adminlte/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css'%}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'registration/adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css'%}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static 'registration/adminlte/plugins/jqvmap/jqvmap.min.css'%}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'registration/adminlte/dist/css/adminlte.min.css'%}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'registration/adminlte/plugins/overlayScrollbars/css/OverlayScrollbars.min.css'%}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static 'registration/adminlte/plugins/daterangepicker/daterangepicker.css'%}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static 'registration/adminlte/plugins/summernote/summernote-bs4.css'%}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  <!-- Bootstrap 4 RTL -->
  <link rel="stylesheet" href="https://cdn.rtlcss.com/bootstrap/v4.2.1/css/bootstrap.min.css">
  <!-- Custom style for RTL -->
  <link rel="stylesheet" href="{% static 'registration/adminlte/dist/css/custom.css'%}">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'account:home' %}" class="nav-link">صفحه اصلی</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'blog:home' %}" target="blank" class="nav-link">نمایش سایت</a>
      </li>
    </ul>


    <!-- Right navbar links -->
    <ul class="navbar-nav mr-auto-navbav">
      <!-- Messages Dropdown Menu -->
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="{% url 'account:logout' %}">
          <i class="fas fa-sign-out-alt"></i>
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  {% include 'registration/sidebar.html' %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">{% block title %} {% endblock %}</h1>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        
        {% block main %}
          
        {% endblock %}
        
        <!-- Main row -->
        <div class="row">
          <!-- Left col -->
          <section class="col-lg-7 connectedSortable">


            

            <!-- /.card -->
          </section>
          <!-- /.Left col -->
          <!-- right col (We are only adding the ID to make the widgets sortable)-->
          <section class="col-lg-5 connectedSortable">


          </section>
          <!-- right col -->
        </div>
        <!-- /.row (main row) -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
   <strong>سامانه اساتید</strong>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'registration/adminlte/plugins/jquery/jquery.min.js'%}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'registration/adminlte/plugins/jquery-ui/jquery-ui.min.js'%}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 rtl -->
<script src="https://cdn.rtlcss.com/bootstrap/v4.2.1/js/bootstrap.min.js"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'registration/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js '%}"></script>
<!-- ChartJS -->
<script src="{% static 'registration/adminlte/plugins/chart.js/Chart.min.js'%}"></script>
<!-- Sparkline -->
<script src="{% static 'registration/adminlte/plugins/sparklines/sparkline.js'%}"></script>
<!-- JQVMap -->
<script src="{% static 'registration/adminlte/plugins/jqvmap/jquery.vmap.min.js'%}"></script>
<script src="{% static 'registration/adminlte/plugins/jqvmap/maps/jquery.vmap.world.js'%}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'registration/adminlte/plugins/jquery-knob/jquery.knob.min.js'%}"></script>
<!-- daterangepicker -->
<script src="{% static 'registration/adminlte/plugins/moment/moment.min.js'%}"></script>
<script src="{% static 'registration/adminlte/plugins/daterangepicker/daterangepicker.js'%}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'registration/adminlte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js'%}"></script>
<!-- Summernote -->
<script src="{% static 'registration/adminlte/plugins/summernote/summernote-bs4.min.js'%}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'registration/adminlte/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js'%}"></script>
<!-- AdminLTE App -->
<script src="{% static 'registration/adminlte/dist/js/adminlte.js'%}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'registration/adminlte/dist/js/pages/dashboard.js'%}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'registration/adminlte/dist/js/demo.js'%}"></script>
</body>
</html>

poll/templates/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load widget_tweaks %}
{% block title %} نظرسنجی{% endblock %}
{% block main %}
<head>
    <style>
        ul.more-ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
        }

        li.more-li {
            float: left;
        }

        li.more-li a {
            display: block;
            color: black;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

        li a:hover {
            background-color: grey;
        }
    </style>
</head>
        <nav class="navbar navbar-default" role="navigation">
            <div class="container">
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'poll:home' %}">خانه</a></li>
                        <li><a href="{% url 'poll:create' %}">ایجاد</a></li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div>
        </nav>
        
        <div class="container">
<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">ایجاد نظرسنجی جدید</h4>
                <ul class="more-ul">
                    <li class="more-li"><a class="active" href="{% url 'poll:home' %}">خانه</a></li>
                    {% if user.is_superuser %}
                    <li class="more-li"><a href="{% url 'poll:create' %}">ایجاد</a></li>
                    {% endif %}                
                </ul>
            </div>
                
            <form method="POST">
                {% csrf_token %}
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label for="question">سوال را در این قسمت تایپ کنید</label>
                                {% render_field form.question class="form-control" rows="3" %}
                            </div>  
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="option1">گزینه اول</label>
                                {% render_field form.option_one class="form-control" %}
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="option2">گزینه دوم</label>
                                {% render_field form.option_two class="form-control" %}
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label for="option3">گزینه سوم</label>
                                {% render_field form.option_three class="form-control" %}
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <hr />
                        <div class="col-lg-4">
                            <button style="margin-left: 0px; margin-right: 148px;" type="submit" class="btn btn-info">ارسال</button>
                        </div>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>
</body>
{% endblock %}

poll/templates/home.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}
نظرسنجی 
{% endblock %}
{% block main %}
<head>
    <style>
ul.more-ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
}

li.more-li {
  float: left;
}

li.more-li a {
  display: block;
  color: black;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

li a:hover {
  background-color: grey;
}
    </style>
</head>
<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">نظرسنجی های موجود</h4>
            <ul class="more-ul">
                <li class="more-li"><a class="active" href="{% url 'poll:home' %}">خانه</a></li>
                {% if user.is_superuser %}
                <li class="more-li"><a href="{% url 'poll:create' %}">ایجاد</a></li>
                {% endif %}
            </ul>
            </div>
            <ul class="list-group">
                {% for poll in polls %}
                <li class="list-group-item">
                    <strong>{{ poll.question }}</strong>
                    <span>
                        <a href="{% url 'poll:vote' poll.id %}" class="btn btn-info btn-xs">رای</a> &nbsp;
                        <a href="{% url 'poll:results' poll.id %}" class="btn btn-default btn-xs">نمایش نتایج</a> &nbsp;
                    </span>
                </li>
                {% endfor %}
            </ul>

        </div>
    </div>
</div>
{% endblock %}


poll/templates/results.html
{% extends "base.html" %}
{% block title %}نظرسنجی{% endblock %}
{% block main %}
<head>
    <style>
        ul.more-ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
        }

        li.more-li {
            float: left;
        }

        li.more-li a {
            display: block;
            color: black;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

        li a:hover {
            background-color: grey;
        }
    </style>
</head>
<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">نتایج نظرسنجی</h4>
                <ul class="more-ul">
                    <li class="more-li"><a class="active" href="{% url 'poll:home' %}">خانه</a></li>
                    {% if user.is_superuser %}
                    <li class="more-li"><a href="{% url 'poll:create' %}">ایجاد</a></li>
                    {% endif %}
                </ul>
            </div>
            <div class="panel-body">
                <h3>{{ poll.question }}</h3>
            </div>
            <ul class="list-group">
                <li class="list-group-item">{{ poll.option_one }} &mdash; <strong>{{ poll.option_one_count }}</strong></li>
                <li class="list-group-item">{{ poll.option_two }} &mdash; <strong>{{ poll.option_two_count }}</strong></li>
                <li class="list-group-item">{{ poll.option_three }} &mdash; <strong>{{ poll.option_three_count }}</strong></li>
            </ul>
            <div class="panel-footer">
                مجموع &mdash; <strong>{{ poll.total }}</strong>
            </div>
        </div>
    </div>
</div>
{% endblock %}

poll/templates/vote.html
{% extends "base.html" %}
{% block title %}نظرسنجی{% endblock %}
{% block main %}
<head>
    <style>
        ul.more-ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
        }

        li.more-li {
            float: left;
        }

        li.more-li a {
            display: block;
            color: black;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

        li a:hover {
            background-color: grey;
        }
    </style>
</head>
<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <ul class="more-ul">
                    <li class="more-li"><a class="active" href="{% url 'poll:home' %}">خانه</a></li>
                        {% if user.is_superuser %}
                        <li class="more-li"><a href="{% url 'poll:create' %}">ایجاد</a></li>
                        {% endif %}
                </ul>
            </div>

            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        <h2>{{ poll.question }}</h2>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <hr />
                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <div class="radio">
                                    <label>
                                        <input type="radio" name="poll" value="option1" required>
                                        {{ poll.option_one }}
                                    </label> &nbsp;
                                    <label>
                                        <input type="radio" name="poll" value="option2">
                                        {{ poll.option_two }}
                                    </label> &nbsp;
                                    <label>
                                        <input type="radio" name="poll" value="option3">
                                        {{ poll.option_three }}
                                    </label> &nbsp;
                                </div>
                            </div>
                            
                            <hr />

                            <button type="submit" class="btn btn-info">
                                ارسال
                            </button>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}